name: Deploy
on:
  push:
    branches:
      - main

jobs:
  pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    
    - name: Install mdBook
      run: cargo install mdbook

    - name: Build book
      run: |
        mdbook build book
    
    - name: Deploy book
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: book/book

